#!/usr/bin/env python3
"""
vLLM Generic Kernel Patcher

Reads a patch_manifest.json and dynamically patches vLLM internal modules
with optimized Triton kernels. No hardcoded op names or types.

The manifest is generated by the LLM Agent in Phase 7, who inspects the
actual vLLM module structure and determines the correct patch targets.

Usage:
    # Apply patches from manifest
    python patch_vllm.py --manifest /path/to/patch_manifest.json

    # As a pre-import for vLLM serve
    python -c "
    from patch_vllm import apply_manifest
    apply_manifest('/path/to/patch_manifest.json')
    "

    # Dry run (validate manifest without patching)
    python patch_vllm.py --manifest patch_manifest.json --dry-run

patch_manifest.json format:
{
  "patches": [
    {
      "kernel_file": "problem_fused_rmsnorm_opt.py",
      "target_module": "vllm.model_executor.layers.layernorm",
      "target_class": "RMSNorm",
      "target_method": "forward_hip",
      "init_args_from": "weight.shape[0]",
      "description": "Replace RMSNorm with fused Triton kernel"
    }
  ]
}
"""
import argparse
import importlib
import json
import os
import sys
from typing import Any


def _load_kernel(kernel_file: str, search_dirs: list[str]) -> Any:
    """Load ModelNew class from a kernel file."""
    module_name = os.path.splitext(os.path.basename(kernel_file))[0]

    # Ensure search dirs are in sys.path
    for d in search_dirs:
        if d not in sys.path:
            sys.path.insert(0, d)

    mod = importlib.import_module(module_name)
    if not hasattr(mod, "ModelNew"):
        raise AttributeError(f"{kernel_file} has no ModelNew class")
    return mod.ModelNew


def _resolve_target(target_module: str, target_class: str):
    """Import target module and get the target class."""
    mod = importlib.import_module(target_module)
    cls = getattr(mod, target_class)
    return mod, cls


def _make_patched_method(original_method, kernel_cls, init_args_from: str | None):
    """
    Create a patched method that wraps the optimized kernel.
    Falls back to original on any error.
    """
    _cache = {}

    def patched(self, *args, **kwargs):
        # Build a cache key from the instance id
        instance_id = id(self)
        if instance_id not in _cache:
            try:
                # Determine init args by evaluating expression on self
                if init_args_from:
                    init_val = eval(f"self.{init_args_from}")
                    if not isinstance(init_val, (list, tuple)):
                        init_val = [init_val]
                    opt = kernel_cls(*init_val)
                else:
                    opt = kernel_cls()

                # Move to same device/dtype as self's first parameter
                for p in getattr(self, "parameters", lambda: [])():
                    opt = opt.to(device=p.device, dtype=p.dtype)
                    break

                # Copy matching weights
                self_state = dict(self.named_parameters())
                for name, param in opt.named_parameters():
                    if name in self_state and self_state[name].shape == param.shape:
                        param.data.copy_(self_state[name].data)

                _cache[instance_id] = opt
            except Exception as e:
                print(f"[patch_vllm] WARN: kernel init failed ({e}), using original")
                _cache[instance_id] = None

        opt = _cache[instance_id]
        if opt is None:
            return original_method(self, *args, **kwargs)

        try:
            return opt(*args, **kwargs)
        except Exception:
            # Fallback on any runtime error
            return original_method(self, *args, **kwargs)

    return patched


def apply_manifest(manifest_path: str, search_dirs: list[str] | None = None,
                   dry_run: bool = False) -> dict:
    """
    Apply all patches described in a manifest file.

    Args:
        manifest_path: Path to patch_manifest.json
        search_dirs: Directories to search for kernel files
        dry_run: If True, validate but don't apply patches

    Returns:
        Dict with patch results: {name: "ok" | "skip" | "fail: reason"}
    """
    with open(manifest_path) as f:
        manifest = json.load(f)

    patches = manifest.get("patches", [])
    if not patches:
        print("[patch_vllm] No patches in manifest")
        return {}

    # Default search dirs: same dir as manifest + parent dirs
    if search_dirs is None:
        manifest_dir = os.path.dirname(os.path.abspath(manifest_path))
        search_dirs = [
            manifest_dir,
            os.path.join(manifest_dir, "..", "problems"),
            os.path.join(manifest_dir, "..", "optimized"),
        ]

    print(f"\n{'='*60}")
    print(f"  vLLM Kernel Patcher (manifest-driven)")
    print(f"  Manifest: {manifest_path}")
    print(f"  Patches:  {len(patches)}")
    print(f"  Dry run:  {dry_run}")
    print(f"{'='*60}\n")

    results = {}
    for i, patch in enumerate(patches, 1):
        name = patch.get("description", patch.get("kernel_file", f"patch_{i}"))
        kernel_file = patch["kernel_file"]
        target_module = patch["target_module"]
        target_class = patch["target_class"]
        target_method = patch["target_method"]
        init_args_from = patch.get("init_args_from")

        print(f"[{i}/{len(patches)}] {name}")
        print(f"  kernel: {kernel_file}")
        print(f"  target: {target_module}.{target_class}.{target_method}")

        try:
            # Load optimized kernel
            kernel_cls = _load_kernel(kernel_file, search_dirs)
            print(f"  kernel class: {kernel_cls}")

            # Resolve target
            mod, cls = _resolve_target(target_module, target_class)
            original = getattr(cls, target_method)
            print(f"  original: {original}")

            if dry_run:
                print(f"  ✓ VALID (dry run, not applied)")
                results[name] = "valid"
                continue

            # Create and apply patch
            patched = _make_patched_method(original, kernel_cls, init_args_from)
            setattr(cls, target_method, patched)
            print(f"  ✓ APPLIED")
            results[name] = "ok"

        except FileNotFoundError:
            print(f"  ✗ SKIP: kernel file not found")
            results[name] = "skip: file not found"
        except AttributeError as e:
            print(f"  ✗ SKIP: {e}")
            results[name] = f"skip: {e}"
        except Exception as e:
            print(f"  ✗ FAIL: {e}")
            results[name] = f"fail: {e}"

    print(f"\n{'='*60}")
    applied = sum(1 for v in results.values() if v == "ok")
    print(f"  Results: {applied}/{len(patches)} patches applied")
    print(f"{'='*60}\n")

    return results


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Apply vLLM kernel patches from manifest")
    parser.add_argument("--manifest", required=True, help="Path to patch_manifest.json")
    parser.add_argument("--search-dir", action="append", default=None,
                        help="Additional directories to search for kernel files")
    parser.add_argument("--dry-run", action="store_true",
                        help="Validate manifest without applying patches")
    args = parser.parse_args()

    results = apply_manifest(
        args.manifest,
        search_dirs=args.search_dir,
        dry_run=args.dry_run,
    )
    # Exit with error if any patch failed
    if any(v.startswith("fail") for v in results.values()):
        sys.exit(1)
